### ISSUE TITLE
Syntax error in browser when using 'voie-pages'

### ISSUE THREAD

**Issue by nandordudas** [brattonross/vite-plugin-voie#21]
In the example below.

If `voie-pages` was not istalled, the error does not exists - only a `Cannot find module 'voie-pages' or its corresponding type declarations.` at `./src/main.ts:8` in vscode (can hide with `// @ts-ignore`).

After `voie-pages` is installed as dev dependency, the error is in the browser's console and only shows a white screen.

```
pnpm: Uncaught SyntaxError: The requested module '/node_modules/.pnpm/voie-pages@0.4.0_vue@3.0.5/node_modules/voie-pages/index.js?v=0.4.0' does not provide an export named 'default'
```

```
yarn: Uncaught SyntaxError: The requested module '/node_modules/voie-pages/index.js?v=0.4.0' does not provide an export named 'default
```

---

The file `install.sh` is not necessary, but makes switching between package managers easily.

```sh
git clone https://github.com/nandordudas/vite-plugin-voie
cd vite-plugin-voie && ./install.sh
```

- Node: v15.5.1
- OS: Manjaro Linux x86_64

**Comment by brattonross** [comment]
Hi, this should be fixed in v0.7.1 by #20

Please can you let me know if the issue still persists?
Thanks 😀

**Comment by brattonross** [comment]
Closing the issue as I believe this should be fixed 😀

**Comment by nandordudas** [comment]
Im sorry!

I did run the code below and no error found, thanks.

```bash
pnpx npm-check-updates -u && pnpm i && pnpm dev
```

**Comment by IlyaSemenov** [comment]
Your forgot to update the plugin's package.json to refer to the new voie-pages.

**Comment by IlyaSemenov** [comment]
Ah, and you never published it. 😃

**Comment by replygirl** [comment]
my guy please publish the update
