### ISSUE TITLE
Nested routes bug

### ISSUE THREAD

**Issue by beres** [brattonross/vite-plugin-voie#27]
Hi Ross,

In a configuration like that:
```
  ├── users/
  │  ├── [id].vue
  │  └── index.vue
  └── users.vue
```
if users.vue contains 
<template>
    <router-view />
</template>

the only visible page is /users/[id].vue  for every path like /users*

Also could be useful omit /users.vue if not needed.

**Comment by fulus06** [comment]
This problem also exists in NuxtJS, 
`
|- demos
    |- _id.vue
    |- index.vue
|- demos,vue
`
Go to the /demos/aa page and you'll see demos.vue again，


nuxtjs:
![image](https://user-images.githubusercontent.com/12890684/105184488-5b382800-5b6a-11eb-9a82-4049b61354ff.png)


voie:
![image](https://user-images.githubusercontent.com/12890684/105184578-75720600-5b6a-11eb-8997-7292700a0a66.png)


==============================

`
|- demos
    |- _id.vue
    |- index.vue
`
![image](https://user-images.githubusercontent.com/12890684/105185071-1234a380-5b6b-11eb-8c01-baab1da873c7.png)

**Comment by brattonross** [comment]
Hi @beres,

I'm possibly not able to see part of your comment, did you mean to type something after "if users.vue contains"?
![image](https://user-images.githubusercontent.com/26525065/106141926-b8cf0480-6168-11eb-9fb9-92cbad706cd8.png)

When running the `nested` example in this repo I'm not seeing this issue. Navigating to `/users` presents me with the `/users/index.vue` component, and navigating to something like `/users/1` presents me with the `/users/[id].vue` component.

Perhaps I am misunderstanding what you are expecting to see?

**Comment by beres** [comment]
Hi @brattonross, 

I'm sorry for the issue, at the time i've tested the code moving it from example directory to antfu/vitesse and it did not work, at the time i've resolved by creating an [id] directory. Now i've tested again copying tha same directory and it works, probably some library version in the path made the difference.

Close the issue, thank you
